### ISSUE TITLE
not shown after nordvpn-bin 3.7.1-1 update

### ISSUE THREAD

**Issue by melkopisi** [alex1701c/NordVPNKrunner#1] opened 2020-04-17 23:46 UTC
Hey first thanks for the amazing tool but i have an issue after i updated nordvpn-bin from AUR as i can't use the runner now when i type vpn it don't show nothing but the runner is enabled

please tell me which logs you want to reproduce this issue, Thanks.

**Comment by alex1701c** [comment] 2020-04-18 06:01
Hey,
And I was able to reproduce this by updating my nordvpn installation and it should be fixed with the latest commit.

And thanks for the feedback 😃

**Comment by melkopisi** [comment] 2020-04-18 18:46
Thanks and sorry for my bad English :smiley: , I noticed now :rofl: .

**Comment by melkopisi** [comment] 2020-04-18 19:00
Sorry, but still not working :neutral_face: i tried both branches non of them fixed my issue

**Closed as completed** 2020-04-18 19:03 UTC

**Comment by alex1701c** [comment] 2020-04-18 19:15
That might be because you didn't restart KRunner?

Can you just rerun the install script?

PS: In the other branch I am currently rewriting most of the plugin, but it is not yet finished 😉

**Comment by melkopisi** [comment] 2020-04-18 19:21
it was my bad  the nordvpn daemon was stopped, it's working fine sorry
